### ISSUE TITLE
Support for a torrent URL in lieu of a magnet link or .torrent file

### ISSUE THREAD

**Issue by noffle** [maxogden/torrent#28]
It would be swell if I could run a command like

```
torrent "http://releases.ubuntu.com/14.10/ubuntu-14.10-desktop-amd64.iso.torrent"
```
and have it grab the torrent file and act as though I had passed in the torrent locally.

**Comment by LinusU** [comment]
Or comply with the unix philosophy and read torrent data from `stdin`.

`curl "http://releases.ubuntu.com/14.10/ubuntu-14.10-desktop-amd64.iso.torrent" | torrent`

**Comment by noffle** [comment]
Neat -- I didn't realize that `torrent` happily read torrent data from `stdin`. Thanks for that.

I think it's reasonable either way, but I suggested the feature because `torrent` already accepts both magnet URLs *and* torrent files.

**Comment by LinusU** [comment]
Sorry, I didn't mean to say that it works, only that I think that is should work.

It does work for `info` and `ls` though :) but not when downloading

**Comment by LinusU** [comment]
See #31

**Comment by LinusU** [comment]
`torrent` now supports reading from stdin and that is the preferred method of downloading torrents from http.

```sh
curl "http://releases.ubuntu.com/14.10/ubuntu-14.10-desktop-amd64.iso.torrent" | torrent
```
