### ISSUE TITLE
License should be a valid SPDX license expression

### ISSUE THREAD

**Issue by LinusU** [maxogden/torrent#36]
npm seems to be complaining about `BSD`, I will need to investigate this

**Comment by LinusU** [comment]
@maxogden Did you mean to release this under the "BSD 2-clause "Simplified" License" (`BSD-2-Clause`) or the "BSD 3-clause "New" or "Revised" License" (`BSD-3-Clause`)?

**Comment by maxogden** [comment]
it should be BSD-3-Clause

On Wednesday, June 17, 2015, Linus Unnebäck <notifications@github.com>
wrote:

> @maxogden <https://github.com/maxogden> Did you mean to release this
> under the "BSD 2-clause "Simplified" License" (BSD-2-Clause) or the "BSD
> 3-clause "New" or "Revised" License" (BSD-3-Clause)?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/maxogden/torrent/issues/36#issuecomment-112707244>.
>


-- 
Sent from my phone

**Comment by LinusU** [comment]
Fixed in 747baaa
